import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FAF6F1',
  surface: '#FFFFFF',
  tan: '#BF9B7A',
  brown: '#593E2E',
  olive: '#555934',
  textPrimary: '#3A2B22',
  textSecondary: '#7A6A5D',
  border: '#E4D8CB',
  danger: '#B3261E',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background, justifyContent: 'center', paddingHorizontal: 28 },
  titulo: { fontSize: 28, fontWeight: '700', color: colors.brown, textAlign: 'center' },
  subtitulo: { fontSize: 15, color: colors.textSecondary, textAlign: 'center', marginTop: 4, marginBottom: 32 },
  input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 12, fontSize: 15, color: colors.textPrimary, marginBottom: 14 },
  botao: { backgroundColor: colors.olive, borderRadius: 10, paddingVertical: 14, alignItems: 'center', marginTop: 8 },
  botaoTexto: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  link: { color: colors.tan, textAlign: 'center', marginTop: 20, fontSize: 14 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 28 },
  saudacao: { fontSize: 22, fontWeight: '700', color: colors.brown },
  emailUsuario: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
  sair: { fontSize: 14, color: colors.olive, fontWeight: '600' },
  secaoTitulo: { fontSize: 16, fontWeight: '600', color: colors.textPrimary, marginBottom: 14 },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 18, marginBottom: 14 },
  cardTitulo: { fontSize: 16, fontWeight: '600', color: colors.brown, marginBottom: 4 },
  cardDescricao: { fontSize: 13, color: colors.textSecondary },
  voltar: { fontSize: 14, color: colors.olive, fontWeight: '600' },
  adicionar: { fontSize: 14, color: colors.olive, fontWeight: '600' },
  formAgenda: { marginBottom: 20 },
  dataBox: { backgroundColor: colors.tan, borderRadius: 8, paddingVertical: 6, paddingHorizontal: 10, marginRight: 14 },
  dataTexto: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },
  cardTipo: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  erro: { color: colors.danger, fontSize: 13, marginBottom: 10 },
  remover: { fontSize: 13, color: colors.danger, fontWeight: '600' },
  espaco: { height: 20 },
  linha: { flexDirection: 'row', alignItems: 'center' },
  linhaEntre: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 14 },
  chip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6, marginRight: 8, marginBottom: 8 },
  chipAtivo: { backgroundColor: colors.olive, borderColor: colors.olive },
  chipTexto: { fontSize: 13, color: colors.textSecondary },
  chipTextoAtivo: { color: '#FFFFFF' },
  riscado: { textDecorationLine: 'line-through', color: colors.textSecondary },
  barra: { height: 8, backgroundColor: colors.border, borderRadius: 4, overflow: 'hidden', marginTop: 8 },
  barraPreenchida: { height: 8, backgroundColor: colors.olive },
  grade: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 20 },
  diaSemana: { width: '14.28%', textAlign: 'center', fontSize: 12, color: colors.textSecondary, marginBottom: 6 },
  celula: { width: '14.28%', aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  celulaAtiva: { backgroundColor: colors.olive },
  celulaTexto: { fontSize: 14, color: colors.textPrimary },
  ponto: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.tan, marginTop: 2 },
  mediaValor: { fontSize: 40, fontWeight: '700', color: colors.brown },
  tempo: { fontSize: 64, fontWeight: '700', color: colors.brown, textAlign: 'center', marginBottom: 24 },
});
